#! /bin/sh

sxhkd &

bspc monitor -d 1 2 3 4 5

bspc config border_width        1
bspc config window_gap          8

#bspc config active_border_color \#00ff00
bspc config normal_border_color \#494946

bspc config split_ratio          0.52
bspc config borderless_monocle  	 true
bspc config gapless_monocle     	 true
bspc config focus_follows_pointer	 true
bspc config click_to_focus		 true
bspc config top_padding 20
bspc config focused_border_color    '#f0f0f0'
bspc config center_pseudo_tiled 	false
bspc config single_monocle 		true

sh .screenlayout/default.sh &
feh --bg-fill ~/Pictures/blur.png &
compton -c -o 0.3 -r 8 & 
xsetroot -cursor_name left_ptr &
polybar top &
